name: Deploy React App (CRA)

on:
  push:
    branches: [ main ]   # Runs when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest   # Use Linux runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24   # 👈 Using Node 24 instead of 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
